package task.repository.model;

import java.math.BigDecimal;

public class CttItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.BELONG_TO_TYPE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String belongToType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String belongToPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.PARENT_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String parentPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.GRADE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.ORDERID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.NAME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.UNIT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CONTRACT_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private BigDecimal contractUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private BigDecimal contractQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private BigDecimal contractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.SIGN_PART_A_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private BigDecimal signPartAPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CREATED_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CREATED_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.REC_VERSION
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.REMARK
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.CORRESPONDING_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String correspondingPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_ITEM.SPARE_FIELD
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    private String spareField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.PKID
     *
     * @return the value of task.CTT_ITEM.PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.PKID
     *
     * @param pkid the value for task.CTT_ITEM.PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.BELONG_TO_TYPE
     *
     * @return the value of task.CTT_ITEM.BELONG_TO_TYPE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getBelongToType() {
        return belongToType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.BELONG_TO_TYPE
     *
     * @param belongToType the value for task.CTT_ITEM.BELONG_TO_TYPE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setBelongToType(String belongToType) {
        this.belongToType = belongToType == null ? null : belongToType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.BELONG_TO_PKID
     *
     * @return the value of task.CTT_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getBelongToPkid() {
        return belongToPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.BELONG_TO_PKID
     *
     * @param belongToPkid the value for task.CTT_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setBelongToPkid(String belongToPkid) {
        this.belongToPkid = belongToPkid == null ? null : belongToPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.PARENT_PKID
     *
     * @return the value of task.CTT_ITEM.PARENT_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getParentPkid() {
        return parentPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.PARENT_PKID
     *
     * @param parentPkid the value for task.CTT_ITEM.PARENT_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setParentPkid(String parentPkid) {
        this.parentPkid = parentPkid == null ? null : parentPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.GRADE
     *
     * @return the value of task.CTT_ITEM.GRADE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.GRADE
     *
     * @param grade the value for task.CTT_ITEM.GRADE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.ORDERID
     *
     * @return the value of task.CTT_ITEM.ORDERID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.ORDERID
     *
     * @param orderid the value for task.CTT_ITEM.ORDERID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.NAME
     *
     * @return the value of task.CTT_ITEM.NAME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.NAME
     *
     * @param name the value for task.CTT_ITEM.NAME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.UNIT
     *
     * @return the value of task.CTT_ITEM.UNIT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.UNIT
     *
     * @param unit the value for task.CTT_ITEM.UNIT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CONTRACT_UNIT_PRICE
     *
     * @return the value of task.CTT_ITEM.CONTRACT_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public BigDecimal getContractUnitPrice() {
        return contractUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CONTRACT_UNIT_PRICE
     *
     * @param contractUnitPrice the value for task.CTT_ITEM.CONTRACT_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setContractUnitPrice(BigDecimal contractUnitPrice) {
        this.contractUnitPrice = contractUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CONTRACT_QUANTITY
     *
     * @return the value of task.CTT_ITEM.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public BigDecimal getContractQuantity() {
        return contractQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CONTRACT_QUANTITY
     *
     * @param contractQuantity the value for task.CTT_ITEM.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setContractQuantity(BigDecimal contractQuantity) {
        this.contractQuantity = contractQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CONTRACT_AMOUNT
     *
     * @return the value of task.CTT_ITEM.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public BigDecimal getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CONTRACT_AMOUNT
     *
     * @param contractAmount the value for task.CTT_ITEM.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setContractAmount(BigDecimal contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.SIGN_PART_A_PRICE
     *
     * @return the value of task.CTT_ITEM.SIGN_PART_A_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public BigDecimal getSignPartAPrice() {
        return signPartAPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.SIGN_PART_A_PRICE
     *
     * @param signPartAPrice the value for task.CTT_ITEM.SIGN_PART_A_PRICE
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setSignPartAPrice(BigDecimal signPartAPrice) {
        this.signPartAPrice = signPartAPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.ARCHIVED_FLAG
     *
     * @return the value of task.CTT_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for task.CTT_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.ORIGIN_FLAG
     *
     * @return the value of task.CTT_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.ORIGIN_FLAG
     *
     * @param originFlag the value for task.CTT_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CREATED_BY
     *
     * @return the value of task.CTT_ITEM.CREATED_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CREATED_BY
     *
     * @param createdBy the value for task.CTT_ITEM.CREATED_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CREATED_TIME
     *
     * @return the value of task.CTT_ITEM.CREATED_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CREATED_TIME
     *
     * @param createdTime the value for task.CTT_ITEM.CREATED_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.LAST_UPD_BY
     *
     * @return the value of task.CTT_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.LAST_UPD_BY
     *
     * @param lastUpdBy the value for task.CTT_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.LAST_UPD_TIME
     *
     * @return the value of task.CTT_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for task.CTT_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.REC_VERSION
     *
     * @return the value of task.CTT_ITEM.REC_VERSION
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.REC_VERSION
     *
     * @param recVersion the value for task.CTT_ITEM.REC_VERSION
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.REMARK
     *
     * @return the value of task.CTT_ITEM.REMARK
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.REMARK
     *
     * @param remark the value for task.CTT_ITEM.REMARK
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.CORRESPONDING_PKID
     *
     * @return the value of task.CTT_ITEM.CORRESPONDING_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getCorrespondingPkid() {
        return correspondingPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.CORRESPONDING_PKID
     *
     * @param correspondingPkid the value for task.CTT_ITEM.CORRESPONDING_PKID
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setCorrespondingPkid(String correspondingPkid) {
        this.correspondingPkid = correspondingPkid == null ? null : correspondingPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_ITEM.SPARE_FIELD
     *
     * @return the value of task.CTT_ITEM.SPARE_FIELD
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public String getSpareField() {
        return spareField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_ITEM.SPARE_FIELD
     *
     * @param spareField the value for task.CTT_ITEM.SPARE_FIELD
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    public void setSpareField(String spareField) {
        this.spareField = spareField == null ? null : spareField.trim();
    }
}