package task.repository.model;

public class CttInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.CTT_TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String cttType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.PARENT_PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String parentPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.ID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.NAME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.SIGN_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.SIGN_PART_A
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String signPartA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.SIGN_PART_B
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String signPartB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.CTT_START_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String cttStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.CTT_END_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String cttEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.ATTACHMENT
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.CREATED_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.CREATED_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.REC_VERSION
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.FLOW_STATUS
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String flowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String flowStatusReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.CTT_INFO.FLOW_STATUS_REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    private String flowStatusRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.PKID
     *
     * @return the value of task.CTT_INFO.PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.PKID
     *
     * @param pkid the value for task.CTT_INFO.PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.CTT_TYPE
     *
     * @return the value of task.CTT_INFO.CTT_TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getCttType() {
        return cttType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.CTT_TYPE
     *
     * @param cttType the value for task.CTT_INFO.CTT_TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setCttType(String cttType) {
        this.cttType = cttType == null ? null : cttType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.PARENT_PKID
     *
     * @return the value of task.CTT_INFO.PARENT_PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getParentPkid() {
        return parentPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.PARENT_PKID
     *
     * @param parentPkid the value for task.CTT_INFO.PARENT_PKID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setParentPkid(String parentPkid) {
        this.parentPkid = parentPkid == null ? null : parentPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.ID
     *
     * @return the value of task.CTT_INFO.ID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.ID
     *
     * @param id the value for task.CTT_INFO.ID
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.NAME
     *
     * @return the value of task.CTT_INFO.NAME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.NAME
     *
     * @param name the value for task.CTT_INFO.NAME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.SIGN_DATE
     *
     * @return the value of task.CTT_INFO.SIGN_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.SIGN_DATE
     *
     * @param signDate the value for task.CTT_INFO.SIGN_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setSignDate(String signDate) {
        this.signDate = signDate == null ? null : signDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.SIGN_PART_A
     *
     * @return the value of task.CTT_INFO.SIGN_PART_A
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getSignPartA() {
        return signPartA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.SIGN_PART_A
     *
     * @param signPartA the value for task.CTT_INFO.SIGN_PART_A
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setSignPartA(String signPartA) {
        this.signPartA = signPartA == null ? null : signPartA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.SIGN_PART_B
     *
     * @return the value of task.CTT_INFO.SIGN_PART_B
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getSignPartB() {
        return signPartB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.SIGN_PART_B
     *
     * @param signPartB the value for task.CTT_INFO.SIGN_PART_B
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setSignPartB(String signPartB) {
        this.signPartB = signPartB == null ? null : signPartB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.CTT_START_DATE
     *
     * @return the value of task.CTT_INFO.CTT_START_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getCttStartDate() {
        return cttStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.CTT_START_DATE
     *
     * @param cttStartDate the value for task.CTT_INFO.CTT_START_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setCttStartDate(String cttStartDate) {
        this.cttStartDate = cttStartDate == null ? null : cttStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.CTT_END_DATE
     *
     * @return the value of task.CTT_INFO.CTT_END_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getCttEndDate() {
        return cttEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.CTT_END_DATE
     *
     * @param cttEndDate the value for task.CTT_INFO.CTT_END_DATE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setCttEndDate(String cttEndDate) {
        this.cttEndDate = cttEndDate == null ? null : cttEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.ATTACHMENT
     *
     * @return the value of task.CTT_INFO.ATTACHMENT
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.ATTACHMENT
     *
     * @param attachment the value for task.CTT_INFO.ATTACHMENT
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.REMARK
     *
     * @return the value of task.CTT_INFO.REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.REMARK
     *
     * @param remark the value for task.CTT_INFO.REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.ARCHIVED_FLAG
     *
     * @return the value of task.CTT_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for task.CTT_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.CREATED_BY
     *
     * @return the value of task.CTT_INFO.CREATED_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.CREATED_BY
     *
     * @param createdBy the value for task.CTT_INFO.CREATED_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.CREATED_TIME
     *
     * @return the value of task.CTT_INFO.CREATED_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.CREATED_TIME
     *
     * @param createdTime the value for task.CTT_INFO.CREATED_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.LAST_UPD_BY
     *
     * @return the value of task.CTT_INFO.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.LAST_UPD_BY
     *
     * @param lastUpdBy the value for task.CTT_INFO.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.LAST_UPD_TIME
     *
     * @return the value of task.CTT_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for task.CTT_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.REC_VERSION
     *
     * @return the value of task.CTT_INFO.REC_VERSION
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.REC_VERSION
     *
     * @param recVersion the value for task.CTT_INFO.REC_VERSION
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.TYPE
     *
     * @return the value of task.CTT_INFO.TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.TYPE
     *
     * @param type the value for task.CTT_INFO.TYPE
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.FLOW_STATUS
     *
     * @return the value of task.CTT_INFO.FLOW_STATUS
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.FLOW_STATUS
     *
     * @param flowStatus the value for task.CTT_INFO.FLOW_STATUS
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setFlowStatus(String flowStatus) {
        this.flowStatus = flowStatus == null ? null : flowStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.FLOW_STATUS_REASON
     *
     * @return the value of task.CTT_INFO.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getFlowStatusReason() {
        return flowStatusReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.FLOW_STATUS_REASON
     *
     * @param flowStatusReason the value for task.CTT_INFO.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setFlowStatusReason(String flowStatusReason) {
        this.flowStatusReason = flowStatusReason == null ? null : flowStatusReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.CTT_INFO.FLOW_STATUS_REMARK
     *
     * @return the value of task.CTT_INFO.FLOW_STATUS_REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public String getFlowStatusRemark() {
        return flowStatusRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.CTT_INFO.FLOW_STATUS_REMARK
     *
     * @param flowStatusRemark the value for task.CTT_INFO.FLOW_STATUS_REMARK
     *
     * @mbggenerated Wed Dec 03 16:31:20 CST 2014
     */
    public void setFlowStatusRemark(String flowStatusRemark) {
        this.flowStatusRemark = flowStatusRemark == null ? null : flowStatusRemark.trim();
    }
}