package task.repository.model;

public class Flow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.INFO_PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String infoPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String firstAppointFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.SEND_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String sendTaskPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.RECV_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String recvTaskPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.FLOW_STATUS
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String flowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.FLOW_STATUS_REASON
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String flowStatusReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.FLOW_STATUS_REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String flowStatusRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FLOW.TID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.PKID
     *
     * @return the value of TASK.FLOW.PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.PKID
     *
     * @param pkid the value for TASK.FLOW.PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.INFO_PKID
     *
     * @return the value of TASK.FLOW.INFO_PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getInfoPkid() {
        return infoPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.INFO_PKID
     *
     * @param infoPkid the value for TASK.FLOW.INFO_PKID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setInfoPkid(String infoPkid) {
        this.infoPkid = infoPkid == null ? null : infoPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.FIRST_APPOINT_FLAG
     *
     * @return the value of TASK.FLOW.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getFirstAppointFlag() {
        return firstAppointFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.FIRST_APPOINT_FLAG
     *
     * @param firstAppointFlag the value for TASK.FLOW.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setFirstAppointFlag(String firstAppointFlag) {
        this.firstAppointFlag = firstAppointFlag == null ? null : firstAppointFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.SEND_TASK_PART
     *
     * @return the value of TASK.FLOW.SEND_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getSendTaskPart() {
        return sendTaskPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.SEND_TASK_PART
     *
     * @param sendTaskPart the value for TASK.FLOW.SEND_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setSendTaskPart(String sendTaskPart) {
        this.sendTaskPart = sendTaskPart == null ? null : sendTaskPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.RECV_TASK_PART
     *
     * @return the value of TASK.FLOW.RECV_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getRecvTaskPart() {
        return recvTaskPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.RECV_TASK_PART
     *
     * @param recvTaskPart the value for TASK.FLOW.RECV_TASK_PART
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setRecvTaskPart(String recvTaskPart) {
        this.recvTaskPart = recvTaskPart == null ? null : recvTaskPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.FLOW_STATUS
     *
     * @return the value of TASK.FLOW.FLOW_STATUS
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.FLOW_STATUS
     *
     * @param flowStatus the value for TASK.FLOW.FLOW_STATUS
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setFlowStatus(String flowStatus) {
        this.flowStatus = flowStatus == null ? null : flowStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.FLOW_STATUS_REASON
     *
     * @return the value of TASK.FLOW.FLOW_STATUS_REASON
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getFlowStatusReason() {
        return flowStatusReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.FLOW_STATUS_REASON
     *
     * @param flowStatusReason the value for TASK.FLOW.FLOW_STATUS_REASON
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setFlowStatusReason(String flowStatusReason) {
        this.flowStatusReason = flowStatusReason == null ? null : flowStatusReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.FLOW_STATUS_REMARK
     *
     * @return the value of TASK.FLOW.FLOW_STATUS_REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getFlowStatusRemark() {
        return flowStatusRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.FLOW_STATUS_REMARK
     *
     * @param flowStatusRemark the value for TASK.FLOW.FLOW_STATUS_REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setFlowStatusRemark(String flowStatusRemark) {
        this.flowStatusRemark = flowStatusRemark == null ? null : flowStatusRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.CREATED_BY
     *
     * @return the value of TASK.FLOW.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.CREATED_BY
     *
     * @param createdBy the value for TASK.FLOW.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.CREATED_TIME
     *
     * @return the value of TASK.FLOW.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.CREATED_TIME
     *
     * @param createdTime the value for TASK.FLOW.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.LAST_UPD_BY
     *
     * @return the value of TASK.FLOW.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.LAST_UPD_BY
     *
     * @param lastUpdBy the value for TASK.FLOW.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.LAST_UPD_TIME
     *
     * @return the value of TASK.FLOW.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for TASK.FLOW.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.REMARK
     *
     * @return the value of TASK.FLOW.REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.REMARK
     *
     * @param remark the value for TASK.FLOW.REMARK
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FLOW.TID
     *
     * @return the value of TASK.FLOW.TID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FLOW.TID
     *
     * @param tid the value for TASK.FLOW.TID
     *
     * @mbggenerated Thu Feb 12 15:04:26 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}