package task.repository.model;

public class Ptenumain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String valuetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enudesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUMAIN.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.ENUTYPE
     *
     * @return the value of TASK.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnutype() {
        return enutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.ENUTYPE
     *
     * @param enutype the value for TASK.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnutype(String enutype) {
        this.enutype = enutype == null ? null : enutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.ENUNAME
     *
     * @return the value of TASK.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnuname() {
        return enuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.ENUNAME
     *
     * @param enuname the value for TASK.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnuname(String enuname) {
        this.enuname = enuname == null ? null : enuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.VALUETYPE
     *
     * @return the value of TASK.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getValuetype() {
        return valuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.VALUETYPE
     *
     * @param valuetype the value for TASK.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setValuetype(String valuetype) {
        this.valuetype = valuetype == null ? null : valuetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.ENUDESC
     *
     * @return the value of TASK.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnudesc() {
        return enudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.ENUDESC
     *
     * @param enudesc the value for TASK.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnudesc(String enudesc) {
        this.enudesc = enudesc == null ? null : enudesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.PKID
     *
     * @return the value of TASK.PTENUMAIN.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.PKID
     *
     * @param pkid the value for TASK.PTENUMAIN.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUMAIN.TID
     *
     * @return the value of TASK.PTENUMAIN.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUMAIN.TID
     *
     * @param tid the value for TASK.PTENUMAIN.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}