package task.repository.model;

public class PtenudetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.ENUITEMVALUE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enuitemvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enutype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.ENUITEMVALUE
     *
     * @return the value of TASK.PTENUDETAIL.ENUITEMVALUE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnuitemvalue() {
        return enuitemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.ENUITEMVALUE
     *
     * @param enuitemvalue the value for TASK.PTENUDETAIL.ENUITEMVALUE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnuitemvalue(String enuitemvalue) {
        this.enuitemvalue = enuitemvalue == null ? null : enuitemvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.ENUTYPE
     *
     * @return the value of TASK.PTENUDETAIL.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnutype() {
        return enutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.ENUTYPE
     *
     * @param enutype the value for TASK.PTENUDETAIL.ENUTYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnutype(String enutype) {
        this.enutype = enutype == null ? null : enutype.trim();
    }
}