package task.repository.model;

public class Ptenudetail extends PtenudetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.ENUITEMLABEL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enuitemlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.ENUITEMDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enuitemdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.DISPNO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private Short dispno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.ENUITEMEXPAND
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String enuitemexpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTENUDETAIL.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.ENUITEMLABEL
     *
     * @return the value of TASK.PTENUDETAIL.ENUITEMLABEL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnuitemlabel() {
        return enuitemlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.ENUITEMLABEL
     *
     * @param enuitemlabel the value for TASK.PTENUDETAIL.ENUITEMLABEL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnuitemlabel(String enuitemlabel) {
        this.enuitemlabel = enuitemlabel == null ? null : enuitemlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.ENUITEMDESC
     *
     * @return the value of TASK.PTENUDETAIL.ENUITEMDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnuitemdesc() {
        return enuitemdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.ENUITEMDESC
     *
     * @param enuitemdesc the value for TASK.PTENUDETAIL.ENUITEMDESC
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnuitemdesc(String enuitemdesc) {
        this.enuitemdesc = enuitemdesc == null ? null : enuitemdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.DISPNO
     *
     * @return the value of TASK.PTENUDETAIL.DISPNO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public Short getDispno() {
        return dispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.DISPNO
     *
     * @param dispno the value for TASK.PTENUDETAIL.DISPNO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setDispno(Short dispno) {
        this.dispno = dispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.ENUITEMEXPAND
     *
     * @return the value of TASK.PTENUDETAIL.ENUITEMEXPAND
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEnuitemexpand() {
        return enuitemexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.ENUITEMEXPAND
     *
     * @param enuitemexpand the value for TASK.PTENUDETAIL.ENUITEMEXPAND
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEnuitemexpand(String enuitemexpand) {
        this.enuitemexpand = enuitemexpand == null ? null : enuitemexpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTENUDETAIL.TID
     *
     * @return the value of TASK.PTENUDETAIL.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTENUDETAIL.TID
     *
     * @param tid the value for TASK.PTENUDETAIL.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}