package task.repository.model;

public class Ptenumain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    private String enutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    private String enuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    private String valuetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    private String enudesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTENUMAIN.ENUTYPE
     *
     * @return the value of task.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public String getEnutype() {
        return enutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTENUMAIN.ENUTYPE
     *
     * @param enutype the value for task.PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public void setEnutype(String enutype) {
        this.enutype = enutype == null ? null : enutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTENUMAIN.ENUNAME
     *
     * @return the value of task.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public String getEnuname() {
        return enuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTENUMAIN.ENUNAME
     *
     * @param enuname the value for task.PTENUMAIN.ENUNAME
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public void setEnuname(String enuname) {
        this.enuname = enuname == null ? null : enuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTENUMAIN.VALUETYPE
     *
     * @return the value of task.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public String getValuetype() {
        return valuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTENUMAIN.VALUETYPE
     *
     * @param valuetype the value for task.PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public void setValuetype(String valuetype) {
        this.valuetype = valuetype == null ? null : valuetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTENUMAIN.ENUDESC
     *
     * @return the value of task.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public String getEnudesc() {
        return enudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTENUMAIN.ENUDESC
     *
     * @param enudesc the value for task.PTENUMAIN.ENUDESC
     *
     * @mbggenerated Wed Aug 27 15:54:09 CST 2014
     */
    public void setEnudesc(String enudesc) {
        this.enudesc = enudesc == null ? null : enudesc.trim();
    }
}