package task.repository.model;

import skyline.platform.db.AbstractBasicBean;
import skyline.platform.db.RecordSet;
import skyline.platform.utils.ActionRequest;

import java.util.List;

public class Pterror extends AbstractBasicBean implements Cloneable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.MOUDLEID
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    private String moudleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.ERRORTYPE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    private String errortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.ERRORINDEX
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    private String errorindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.MESSAGE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.FILL1
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    private String fill1;

    public static final String TABLENAME = "pterror";

    public String getTableName() {
        return TABLENAME;
    }

    public void addObject(List list, RecordSet rs) {
        Pterror abb = new Pterror();
        abb.moudleid = rs.getString("moudleid");
        abb.errortype = rs.getString("errortype");
        abb.errorindex = rs.getString("errorindex");
        abb.message = rs.getString("message");
        list.add(abb);
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.MOUDLEID
     *
     * @return the value of PTERROR.MOUDLEID
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public String getMoudleid() {
        return moudleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.MOUDLEID
     *
     * @param moudleid the value for PTERROR.MOUDLEID
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public void setMoudleid(String moudleid) {
        this.moudleid = moudleid == null ? null : moudleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.ERRORTYPE
     *
     * @return the value of PTERROR.ERRORTYPE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public String getErrortype() {
        return errortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.ERRORTYPE
     *
     * @param errortype the value for PTERROR.ERRORTYPE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public void setErrortype(String errortype) {
        this.errortype = errortype == null ? null : errortype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.ERRORINDEX
     *
     * @return the value of PTERROR.ERRORINDEX
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public String getErrorindex() {
        return errorindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.ERRORINDEX
     *
     * @param errorindex the value for PTERROR.ERRORINDEX
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public void setErrorindex(String errorindex) {
        this.errorindex = errorindex == null ? null : errorindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.MESSAGE
     *
     * @return the value of PTERROR.MESSAGE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.MESSAGE
     *
     * @param message the value for PTERROR.MESSAGE
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.FILL1
     *
     * @return the value of PTERROR.FILL1
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public String getFill1() {
        return fill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.FILL1
     *
     * @param fill1 the value for PTERROR.FILL1
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    public void setFill1(String fill1) {
        this.fill1 = fill1 == null ? null : fill1.trim();
    }

    public void init(int i, ActionRequest actionRequest)
            throws Exception {
        if (actionRequest.getFieldValue(i, "moudleid") != null) {
            this.setMoudleid(actionRequest.getFieldValue(i, "moudleid"));
        }

        if (actionRequest.getFieldValue(i, "errortype") != null) {
            this.setErrortype(actionRequest.getFieldValue(i, "errortype"));
        }

        if (actionRequest.getFieldValue(i, "errorindex") != null) {
            this.setErrorindex(actionRequest.getFieldValue(i, "errorindex"));
        }

        if (actionRequest.getFieldValue(i, "message") != null) {
            this.setMessage(actionRequest.getFieldValue(i, "message"));
        }
    }

    public void init(ActionRequest actionRequest) throws Exception {
        this.init(0, actionRequest);
    }

    public void initAll(int i, ActionRequest actionRequest)
            throws Exception {
        if (actionRequest.getFieldValue(i, "moudleid") != null) {
            this.setMoudleid(actionRequest.getFieldValue(i, "moudleid"));
        } else {
            this.setMoudleid(null);
        }

        if (actionRequest.getFieldValue(i, "errortype") != null) {
            this.setErrortype(actionRequest.getFieldValue(i, "errortype"));
        } else {
            this.setErrortype(null);
        }

        if (actionRequest.getFieldValue(i, "errorindex") != null) {
            this.setErrorindex(actionRequest.getFieldValue(i, "errorindex"));
        } else {
            this.setErrorindex(null);
        }

        if (actionRequest.getFieldValue(i, "message") != null) {
            this.setMessage(actionRequest.getFieldValue(i, "message"));
        } else {
            this.setMessage(null);
        }
    }

    public void initAll(ActionRequest actionRequest) throws Exception {
        this.initAll(0, actionRequest);
    }

    public Object clone() throws CloneNotSupportedException {
        Pterror obj = (Pterror) super.clone();
        obj.setMoudleid(obj.moudleid);
        obj.setErrortype(obj.errortype);
        obj.setErrorindex(obj.errorindex);
        obj.setMessage(obj.message);
        return obj;
    }
}