package task.repository.model;

public class Ptmenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.PKID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.PARENTMENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String parentmenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENULEVEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private Integer menulevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.ISLEAF
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private Integer isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENUDESC
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String menudesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENULABEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String menulabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.INFOTYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String flowstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String targetmachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENUACTION
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String menuaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.OPENWINDOW
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String openwindow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private Integer windowwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private Integer windowheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.LEVELIDX
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private Integer levelidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PTMENU.MENU_TYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    private String menuType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.PKID
     *
     * @return the value of task.PTMENU.PKID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.PKID
     *
     * @param pkid the value for task.PTMENU.PKID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENUID
     *
     * @return the value of task.PTMENU.MENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENUID
     *
     * @param menuid the value for task.PTMENU.MENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.PARENTMENUID
     *
     * @return the value of task.PTMENU.PARENTMENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getParentmenuid() {
        return parentmenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.PARENTMENUID
     *
     * @param parentmenuid the value for task.PTMENU.PARENTMENUID
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setParentmenuid(String parentmenuid) {
        this.parentmenuid = parentmenuid == null ? null : parentmenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENULEVEL
     *
     * @return the value of task.PTMENU.MENULEVEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public Integer getMenulevel() {
        return menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENULEVEL
     *
     * @param menulevel the value for task.PTMENU.MENULEVEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenulevel(Integer menulevel) {
        this.menulevel = menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.ISLEAF
     *
     * @return the value of task.PTMENU.ISLEAF
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public Integer getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.ISLEAF
     *
     * @param isleaf the value for task.PTMENU.ISLEAF
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setIsleaf(Integer isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENUDESC
     *
     * @return the value of task.PTMENU.MENUDESC
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getMenudesc() {
        return menudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENUDESC
     *
     * @param menudesc the value for task.PTMENU.MENUDESC
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenudesc(String menudesc) {
        this.menudesc = menudesc == null ? null : menudesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENULABEL
     *
     * @return the value of task.PTMENU.MENULABEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getMenulabel() {
        return menulabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENULABEL
     *
     * @param menulabel the value for task.PTMENU.MENULABEL
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenulabel(String menulabel) {
        this.menulabel = menulabel == null ? null : menulabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.INFOTYPE
     *
     * @return the value of task.PTMENU.INFOTYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.INFOTYPE
     *
     * @param infotype the value for task.PTMENU.INFOTYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setInfotype(String infotype) {
        this.infotype = infotype == null ? null : infotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.FLOWSTATUS
     *
     * @return the value of task.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.FLOWSTATUS
     *
     * @param flowstatus the value for task.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setFlowstatus(String flowstatus) {
        this.flowstatus = flowstatus == null ? null : flowstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.TARGETMACHINE
     *
     * @return the value of task.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getTargetmachine() {
        return targetmachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.TARGETMACHINE
     *
     * @param targetmachine the value for task.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setTargetmachine(String targetmachine) {
        this.targetmachine = targetmachine == null ? null : targetmachine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENUACTION
     *
     * @return the value of task.PTMENU.MENUACTION
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getMenuaction() {
        return menuaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENUACTION
     *
     * @param menuaction the value for task.PTMENU.MENUACTION
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenuaction(String menuaction) {
        this.menuaction = menuaction == null ? null : menuaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.OPENWINDOW
     *
     * @return the value of task.PTMENU.OPENWINDOW
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getOpenwindow() {
        return openwindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.OPENWINDOW
     *
     * @param openwindow the value for task.PTMENU.OPENWINDOW
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setOpenwindow(String openwindow) {
        this.openwindow = openwindow == null ? null : openwindow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.WINDOWWIDTH
     *
     * @return the value of task.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public Integer getWindowwidth() {
        return windowwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.WINDOWWIDTH
     *
     * @param windowwidth the value for task.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setWindowwidth(Integer windowwidth) {
        this.windowwidth = windowwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.WINDOWHEIGHT
     *
     * @return the value of task.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public Integer getWindowheight() {
        return windowheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.WINDOWHEIGHT
     *
     * @param windowheight the value for task.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setWindowheight(Integer windowheight) {
        this.windowheight = windowheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.LEVELIDX
     *
     * @return the value of task.PTMENU.LEVELIDX
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public Integer getLevelidx() {
        return levelidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.LEVELIDX
     *
     * @param levelidx the value for task.PTMENU.LEVELIDX
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setLevelidx(Integer levelidx) {
        this.levelidx = levelidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PTMENU.MENU_TYPE
     *
     * @return the value of task.PTMENU.MENU_TYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PTMENU.MENU_TYPE
     *
     * @param menuType the value for task.PTMENU.MENU_TYPE
     *
     * @mbggenerated Mon Sep 22 08:51:24 CST 2014
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }
}