package task.repository.model;

public class Ptmenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.PKID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.TID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.MENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.PARENTMENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String parentmenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.MENULEVEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private Integer menulevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.ISLEAF
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private Integer isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.MENUDESC
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String menudesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.MENULABEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String menulabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.INFOTYPE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String flowstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String targetmachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.MENUACTION
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String menuaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.OPENWINDOW
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private String openwindow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private Integer windowwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private Integer windowheight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.PTMENU.LEVELIDX
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    private Integer levelidx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.PKID
     *
     * @return the value of TASK.PTMENU.PKID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.PKID
     *
     * @param pkid the value for TASK.PTMENU.PKID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.TID
     *
     * @return the value of TASK.PTMENU.TID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.TID
     *
     * @param tid the value for TASK.PTMENU.TID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.MENUID
     *
     * @return the value of TASK.PTMENU.MENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.MENUID
     *
     * @param menuid the value for TASK.PTMENU.MENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.PARENTMENUID
     *
     * @return the value of TASK.PTMENU.PARENTMENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getParentmenuid() {
        return parentmenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.PARENTMENUID
     *
     * @param parentmenuid the value for TASK.PTMENU.PARENTMENUID
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setParentmenuid(String parentmenuid) {
        this.parentmenuid = parentmenuid == null ? null : parentmenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.MENULEVEL
     *
     * @return the value of TASK.PTMENU.MENULEVEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public Integer getMenulevel() {
        return menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.MENULEVEL
     *
     * @param menulevel the value for TASK.PTMENU.MENULEVEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setMenulevel(Integer menulevel) {
        this.menulevel = menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.ISLEAF
     *
     * @return the value of TASK.PTMENU.ISLEAF
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public Integer getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.ISLEAF
     *
     * @param isleaf the value for TASK.PTMENU.ISLEAF
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setIsleaf(Integer isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.MENUDESC
     *
     * @return the value of TASK.PTMENU.MENUDESC
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getMenudesc() {
        return menudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.MENUDESC
     *
     * @param menudesc the value for TASK.PTMENU.MENUDESC
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setMenudesc(String menudesc) {
        this.menudesc = menudesc == null ? null : menudesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.MENULABEL
     *
     * @return the value of TASK.PTMENU.MENULABEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getMenulabel() {
        return menulabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.MENULABEL
     *
     * @param menulabel the value for TASK.PTMENU.MENULABEL
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setMenulabel(String menulabel) {
        this.menulabel = menulabel == null ? null : menulabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.INFOTYPE
     *
     * @return the value of TASK.PTMENU.INFOTYPE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.INFOTYPE
     *
     * @param infotype the value for TASK.PTMENU.INFOTYPE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setInfotype(String infotype) {
        this.infotype = infotype == null ? null : infotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.FLOWSTATUS
     *
     * @return the value of TASK.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.FLOWSTATUS
     *
     * @param flowstatus the value for TASK.PTMENU.FLOWSTATUS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setFlowstatus(String flowstatus) {
        this.flowstatus = flowstatus == null ? null : flowstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.TARGETMACHINE
     *
     * @return the value of TASK.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getTargetmachine() {
        return targetmachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.TARGETMACHINE
     *
     * @param targetmachine the value for TASK.PTMENU.TARGETMACHINE
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setTargetmachine(String targetmachine) {
        this.targetmachine = targetmachine == null ? null : targetmachine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.MENUACTION
     *
     * @return the value of TASK.PTMENU.MENUACTION
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getMenuaction() {
        return menuaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.MENUACTION
     *
     * @param menuaction the value for TASK.PTMENU.MENUACTION
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setMenuaction(String menuaction) {
        this.menuaction = menuaction == null ? null : menuaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.OPENWINDOW
     *
     * @return the value of TASK.PTMENU.OPENWINDOW
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public String getOpenwindow() {
        return openwindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.OPENWINDOW
     *
     * @param openwindow the value for TASK.PTMENU.OPENWINDOW
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setOpenwindow(String openwindow) {
        this.openwindow = openwindow == null ? null : openwindow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.WINDOWWIDTH
     *
     * @return the value of TASK.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public Integer getWindowwidth() {
        return windowwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.WINDOWWIDTH
     *
     * @param windowwidth the value for TASK.PTMENU.WINDOWWIDTH
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setWindowwidth(Integer windowwidth) {
        this.windowwidth = windowwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.WINDOWHEIGHT
     *
     * @return the value of TASK.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public Integer getWindowheight() {
        return windowheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.WINDOWHEIGHT
     *
     * @param windowheight the value for TASK.PTMENU.WINDOWHEIGHT
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setWindowheight(Integer windowheight) {
        this.windowheight = windowheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.PTMENU.LEVELIDX
     *
     * @return the value of TASK.PTMENU.LEVELIDX
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public Integer getLevelidx() {
        return levelidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.PTMENU.LEVELIDX
     *
     * @param levelidx the value for TASK.PTMENU.LEVELIDX
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    public void setLevelidx(Integer levelidx) {
        this.levelidx = levelidx;
    }
}