package task.repository.model;

public class WorkorderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String belongToPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String parentPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String itemContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    private Integer recVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.PKID
     *
     * @param pkid the value for TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.TID
     *
     * @return the value of TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.TID
     *
     * @param tid the value for TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getBelongToPkid() {
        return belongToPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @param belongToPkid the value for TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setBelongToPkid(String belongToPkid) {
        this.belongToPkid = belongToPkid == null ? null : belongToPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getParentPkid() {
        return parentPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @param parentPkid the value for TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setParentPkid(String parentPkid) {
        this.parentPkid = parentPkid == null ? null : parentPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @return the value of TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @param grade the value for TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @return the value of TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @param orderid the value for TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ITEM_CONTENT
     *
     * @return the value of TASK.WORKORDER_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getItemContent() {
        return itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ITEM_CONTENT
     *
     * @param itemContent the value for TASK.WORKORDER_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setItemContent(String itemContent) {
        this.itemContent = itemContent == null ? null : itemContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @return the value of TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @return the value of TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @param originFlag the value for TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @return the value of TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @param createdBy the value for TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @return the value of TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @param createdTime the value for TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @return the value of TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @param lastUpdBy the value for TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @return the value of TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @return the value of TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @param recVersion the value for TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }
}