package task.repository.model;

public class WorkorderAppoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.INFO_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String infoPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String firstAppointFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.SEND_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String sendTaskPartPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.RECV_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String recvTaskPartPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.CREATED_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.CREATED_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.REMARK
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.REC_VERSION
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.RECV_TASK_FINISH_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String recvTaskFinishFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT.TID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT.PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.PKID
     *
     * @param pkid the value for TASK.WORKORDER_APPOINT.PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.INFO_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT.INFO_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getInfoPkid() {
        return infoPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.INFO_PKID
     *
     * @param infoPkid the value for TASK.WORKORDER_APPOINT.INFO_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setInfoPkid(String infoPkid) {
        this.infoPkid = infoPkid == null ? null : infoPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.FIRST_APPOINT_FLAG
     *
     * @return the value of TASK.WORKORDER_APPOINT.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getFirstAppointFlag() {
        return firstAppointFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.FIRST_APPOINT_FLAG
     *
     * @param firstAppointFlag the value for TASK.WORKORDER_APPOINT.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setFirstAppointFlag(String firstAppointFlag) {
        this.firstAppointFlag = firstAppointFlag == null ? null : firstAppointFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.SEND_TASK_PART_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT.SEND_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getSendTaskPartPkid() {
        return sendTaskPartPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.SEND_TASK_PART_PKID
     *
     * @param sendTaskPartPkid the value for TASK.WORKORDER_APPOINT.SEND_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setSendTaskPartPkid(String sendTaskPartPkid) {
        this.sendTaskPartPkid = sendTaskPartPkid == null ? null : sendTaskPartPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.RECV_TASK_PART_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT.RECV_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getRecvTaskPartPkid() {
        return recvTaskPartPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.RECV_TASK_PART_PKID
     *
     * @param recvTaskPartPkid the value for TASK.WORKORDER_APPOINT.RECV_TASK_PART_PKID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setRecvTaskPartPkid(String recvTaskPartPkid) {
        this.recvTaskPartPkid = recvTaskPartPkid == null ? null : recvTaskPartPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.ARCHIVED_FLAG
     *
     * @return the value of TASK.WORKORDER_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for TASK.WORKORDER_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.CREATED_BY
     *
     * @return the value of TASK.WORKORDER_APPOINT.CREATED_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.CREATED_BY
     *
     * @param createdBy the value for TASK.WORKORDER_APPOINT.CREATED_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.CREATED_TIME
     *
     * @return the value of TASK.WORKORDER_APPOINT.CREATED_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.CREATED_TIME
     *
     * @param createdTime the value for TASK.WORKORDER_APPOINT.CREATED_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.LAST_UPD_BY
     *
     * @return the value of TASK.WORKORDER_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.LAST_UPD_BY
     *
     * @param lastUpdBy the value for TASK.WORKORDER_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.LAST_UPD_TIME
     *
     * @return the value of TASK.WORKORDER_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for TASK.WORKORDER_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.REMARK
     *
     * @return the value of TASK.WORKORDER_APPOINT.REMARK
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.REMARK
     *
     * @param remark the value for TASK.WORKORDER_APPOINT.REMARK
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.REC_VERSION
     *
     * @return the value of TASK.WORKORDER_APPOINT.REC_VERSION
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.REC_VERSION
     *
     * @param recVersion the value for TASK.WORKORDER_APPOINT.REC_VERSION
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.RECV_TASK_FINISH_FLAG
     *
     * @return the value of TASK.WORKORDER_APPOINT.RECV_TASK_FINISH_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getRecvTaskFinishFlag() {
        return recvTaskFinishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.RECV_TASK_FINISH_FLAG
     *
     * @param recvTaskFinishFlag the value for TASK.WORKORDER_APPOINT.RECV_TASK_FINISH_FLAG
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setRecvTaskFinishFlag(String recvTaskFinishFlag) {
        this.recvTaskFinishFlag = recvTaskFinishFlag == null ? null : recvTaskFinishFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT.TID
     *
     * @return the value of TASK.WORKORDER_APPOINT.TID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT.TID
     *
     * @param tid the value for TASK.WORKORDER_APPOINT.TID
     *
     * @mbggenerated Sun Mar 01 16:04:00 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}