package task.repository.model;

import java.math.BigDecimal;

public class WorkorderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String belongToPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String parentPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.UNIT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.UNIT_PRICE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.QUANTITY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.AMOUNT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.PKID
     *
     * @param pkid the value for TASK.WORKORDER_ITEM.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getBelongToPkid() {
        return belongToPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @param belongToPkid the value for TASK.WORKORDER_ITEM.BELONG_TO_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setBelongToPkid(String belongToPkid) {
        this.belongToPkid = belongToPkid == null ? null : belongToPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @return the value of TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getParentPkid() {
        return parentPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @param parentPkid the value for TASK.WORKORDER_ITEM.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setParentPkid(String parentPkid) {
        this.parentPkid = parentPkid == null ? null : parentPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @return the value of TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.GRADE
     *
     * @param grade the value for TASK.WORKORDER_ITEM.GRADE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @return the value of TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ORDERID
     *
     * @param orderid the value for TASK.WORKORDER_ITEM.ORDERID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.NAME
     *
     * @return the value of TASK.WORKORDER_ITEM.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.NAME
     *
     * @param name the value for TASK.WORKORDER_ITEM.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.UNIT
     *
     * @return the value of TASK.WORKORDER_ITEM.UNIT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.UNIT
     *
     * @param unit the value for TASK.WORKORDER_ITEM.UNIT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.UNIT_PRICE
     *
     * @return the value of TASK.WORKORDER_ITEM.UNIT_PRICE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.UNIT_PRICE
     *
     * @param unitPrice the value for TASK.WORKORDER_ITEM.UNIT_PRICE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.QUANTITY
     *
     * @return the value of TASK.WORKORDER_ITEM.QUANTITY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.QUANTITY
     *
     * @param quantity the value for TASK.WORKORDER_ITEM.QUANTITY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.AMOUNT
     *
     * @return the value of TASK.WORKORDER_ITEM.AMOUNT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.AMOUNT
     *
     * @param amount the value for TASK.WORKORDER_ITEM.AMOUNT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @return the value of TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for TASK.WORKORDER_ITEM.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @return the value of TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @param originFlag the value for TASK.WORKORDER_ITEM.ORIGIN_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @return the value of TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @param createdBy the value for TASK.WORKORDER_ITEM.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @return the value of TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @param createdTime the value for TASK.WORKORDER_ITEM.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @return the value of TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @param lastUpdBy the value for TASK.WORKORDER_ITEM.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @return the value of TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for TASK.WORKORDER_ITEM.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @return the value of TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @param recVersion the value for TASK.WORKORDER_ITEM.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.REMARK
     *
     * @return the value of TASK.WORKORDER_ITEM.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.REMARK
     *
     * @param remark the value for TASK.WORKORDER_ITEM.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_ITEM.TID
     *
     * @return the value of TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_ITEM.TID
     *
     * @param tid the value for TASK.WORKORDER_ITEM.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}