package task.repository.model;

public class WorkorderAppointHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.INFO_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String infoPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.INFO_ID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.INFO_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String infoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String firstAppointFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.RECV_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String recvTaskPartPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.SEND_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String sendTaskPartPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.FINISH_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String finishFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.CREATED_TIME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.REMARK
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.OPER_TYPE
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_APPOINT_HIS.TID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.PKID
     *
     * @param pkid the value for TASK.WORKORDER_APPOINT_HIS.PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.INFO_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getInfoPkid() {
        return infoPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_PKID
     *
     * @param infoPkid the value for TASK.WORKORDER_APPOINT_HIS.INFO_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setInfoPkid(String infoPkid) {
        this.infoPkid = infoPkid == null ? null : infoPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_ID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.INFO_ID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_ID
     *
     * @param infoId the value for TASK.WORKORDER_APPOINT_HIS.INFO_ID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_NAME
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.INFO_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getInfoName() {
        return infoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.INFO_NAME
     *
     * @param infoName the value for TASK.WORKORDER_APPOINT_HIS.INFO_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setInfoName(String infoName) {
        this.infoName = infoName == null ? null : infoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.FIRST_APPOINT_FLAG
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getFirstAppointFlag() {
        return firstAppointFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.FIRST_APPOINT_FLAG
     *
     * @param firstAppointFlag the value for TASK.WORKORDER_APPOINT_HIS.FIRST_APPOINT_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setFirstAppointFlag(String firstAppointFlag) {
        this.firstAppointFlag = firstAppointFlag == null ? null : firstAppointFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.RECV_TASK_PART_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.RECV_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getRecvTaskPartPkid() {
        return recvTaskPartPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.RECV_TASK_PART_PKID
     *
     * @param recvTaskPartPkid the value for TASK.WORKORDER_APPOINT_HIS.RECV_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setRecvTaskPartPkid(String recvTaskPartPkid) {
        this.recvTaskPartPkid = recvTaskPartPkid == null ? null : recvTaskPartPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.SEND_TASK_PART_PKID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.SEND_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getSendTaskPartPkid() {
        return sendTaskPartPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.SEND_TASK_PART_PKID
     *
     * @param sendTaskPartPkid the value for TASK.WORKORDER_APPOINT_HIS.SEND_TASK_PART_PKID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setSendTaskPartPkid(String sendTaskPartPkid) {
        this.sendTaskPartPkid = sendTaskPartPkid == null ? null : sendTaskPartPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.FINISH_FLAG
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.FINISH_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getFinishFlag() {
        return finishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.FINISH_FLAG
     *
     * @param finishFlag the value for TASK.WORKORDER_APPOINT_HIS.FINISH_FLAG
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setFinishFlag(String finishFlag) {
        this.finishFlag = finishFlag == null ? null : finishFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.CREATED_BY
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY
     *
     * @param createdBy the value for TASK.WORKORDER_APPOINT_HIS.CREATED_BY
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY_NAME
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.CREATED_BY_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_BY_NAME
     *
     * @param createdByName the value for TASK.WORKORDER_APPOINT_HIS.CREATED_BY_NAME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_TIME
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.CREATED_TIME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.CREATED_TIME
     *
     * @param createdTime the value for TASK.WORKORDER_APPOINT_HIS.CREATED_TIME
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.REMARK
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.REMARK
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.REMARK
     *
     * @param remark the value for TASK.WORKORDER_APPOINT_HIS.REMARK
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.OPER_TYPE
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.OPER_TYPE
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.OPER_TYPE
     *
     * @param operType the value for TASK.WORKORDER_APPOINT_HIS.OPER_TYPE
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_APPOINT_HIS.TID
     *
     * @return the value of TASK.WORKORDER_APPOINT_HIS.TID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_APPOINT_HIS.TID
     *
     * @param tid the value for TASK.WORKORDER_APPOINT_HIS.TID
     *
     * @mbggenerated Fri Feb 27 01:18:10 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}