package task.repository.model;

public class WorkorderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String parentPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.ID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.TYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.SIGN_DATE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.START_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.END_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.ATTACHMENT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.WORKORDER_INFO.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.PKID
     *
     * @return the value of TASK.WORKORDER_INFO.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.PKID
     *
     * @param pkid the value for TASK.WORKORDER_INFO.PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.PARENT_PKID
     *
     * @return the value of TASK.WORKORDER_INFO.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getParentPkid() {
        return parentPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.PARENT_PKID
     *
     * @param parentPkid the value for TASK.WORKORDER_INFO.PARENT_PKID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setParentPkid(String parentPkid) {
        this.parentPkid = parentPkid == null ? null : parentPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.ID
     *
     * @return the value of TASK.WORKORDER_INFO.ID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.ID
     *
     * @param id the value for TASK.WORKORDER_INFO.ID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.NAME
     *
     * @return the value of TASK.WORKORDER_INFO.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.NAME
     *
     * @param name the value for TASK.WORKORDER_INFO.NAME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.TYPE
     *
     * @return the value of TASK.WORKORDER_INFO.TYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.TYPE
     *
     * @param type the value for TASK.WORKORDER_INFO.TYPE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.SIGN_DATE
     *
     * @return the value of TASK.WORKORDER_INFO.SIGN_DATE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.SIGN_DATE
     *
     * @param signDate the value for TASK.WORKORDER_INFO.SIGN_DATE
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setSignDate(String signDate) {
        this.signDate = signDate == null ? null : signDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.START_TIME
     *
     * @return the value of TASK.WORKORDER_INFO.START_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.START_TIME
     *
     * @param startTime the value for TASK.WORKORDER_INFO.START_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.END_TIME
     *
     * @return the value of TASK.WORKORDER_INFO.END_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.END_TIME
     *
     * @param endTime the value for TASK.WORKORDER_INFO.END_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.ATTACHMENT
     *
     * @return the value of TASK.WORKORDER_INFO.ATTACHMENT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.ATTACHMENT
     *
     * @param attachment the value for TASK.WORKORDER_INFO.ATTACHMENT
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.REMARK
     *
     * @return the value of TASK.WORKORDER_INFO.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.REMARK
     *
     * @param remark the value for TASK.WORKORDER_INFO.REMARK
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.ARCHIVED_FLAG
     *
     * @return the value of TASK.WORKORDER_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for TASK.WORKORDER_INFO.ARCHIVED_FLAG
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.CREATED_BY
     *
     * @return the value of TASK.WORKORDER_INFO.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.CREATED_BY
     *
     * @param createdBy the value for TASK.WORKORDER_INFO.CREATED_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.CREATED_TIME
     *
     * @return the value of TASK.WORKORDER_INFO.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.CREATED_TIME
     *
     * @param createdTime the value for TASK.WORKORDER_INFO.CREATED_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.LAST_UPD_BY
     *
     * @return the value of TASK.WORKORDER_INFO.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.LAST_UPD_BY
     *
     * @param lastUpdBy the value for TASK.WORKORDER_INFO.LAST_UPD_BY
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.LAST_UPD_TIME
     *
     * @return the value of TASK.WORKORDER_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for TASK.WORKORDER_INFO.LAST_UPD_TIME
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.REC_VERSION
     *
     * @return the value of TASK.WORKORDER_INFO.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.REC_VERSION
     *
     * @param recVersion the value for TASK.WORKORDER_INFO.REC_VERSION
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.WORKORDER_INFO.TID
     *
     * @return the value of TASK.WORKORDER_INFO.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.WORKORDER_INFO.TID
     *
     * @param tid the value for TASK.WORKORDER_INFO.TID
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}