package task.repository.dao;

import task.repository.model.Dept;
import task.repository.model.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    Dept selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.DEPT
     *
     * @mbggenerated Thu Aug 21 20:40:01 CST 2014
     */
    int updateByPrimaryKey(Dept record);
}