package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.Flow;
import task.repository.model.FlowExample;

public interface FlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int countByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insert(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insertSelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    List<Flow> selectByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    Flow selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") Flow record, @Param("example") FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExample(@Param("record") Flow record, @Param("example") FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKeySelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKey(Flow record);
}