package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.FlowHis;
import task.repository.model.FlowHisExample;

public interface FlowHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int countByExample(FlowHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int deleteByExample(FlowHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int insert(FlowHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int insertSelective(FlowHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    List<FlowHis> selectByExample(FlowHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    FlowHis selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") FlowHis record, @Param("example") FlowHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int updateByExample(@Param("record") FlowHis record, @Param("example") FlowHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int updateByPrimaryKeySelective(FlowHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.FLOW_HIS
     *
     * @mbggenerated Fri Feb 13 17:43:57 CST 2015
     */
    int updateByPrimaryKey(FlowHis record);
}