package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.OperRes;
import task.repository.model.OperResExample;

public interface OperResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int countByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int deleteByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int insert(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int insertSelective(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    List<OperRes> selectByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    OperRes selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") OperRes record, @Param("example") OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int updateByExample(@Param("record") OperRes record, @Param("example") OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER_RES
     *
     * @mbggenerated Wed Feb 25 13:37:00 CST 2015
     */
    int updateByPrimaryKey(OperRes record);
}