package task.repository.dao;

import task.repository.model.Ptenudetail;
import task.repository.model.PtenudetailExample;
import task.repository.model.PtenudetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtenudetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int countByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int deleteByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int deleteByPrimaryKey(PtenudetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int insert(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int insertSelective(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    List<Ptenudetail> selectByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    Ptenudetail selectByPrimaryKey(PtenudetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") Ptenudetail record, @Param("example") PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int updateByExample(@Param("record") Ptenudetail record, @Param("example") PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int updateByPrimaryKeySelective(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.PTENUDETAIL
     *
     * @mbggenerated Wed Aug 27 15:55:19 CST 2014
     */
    int updateByPrimaryKey(Ptenudetail record);
}