package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.Ptenudetail;
import task.repository.model.PtenudetailExample;
import task.repository.model.PtenudetailKey;

public interface PtenudetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int countByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByPrimaryKey(PtenudetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insert(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insertSelective(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    List<Ptenudetail> selectByExample(PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    Ptenudetail selectByPrimaryKey(PtenudetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ptenudetail record, @Param("example") PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExample(@Param("record") Ptenudetail record, @Param("example") PtenudetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKeySelective(Ptenudetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.PTENUDETAIL
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKey(Ptenudetail record);
}