package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.Ptlogicact;
import task.repository.model.PtlogicactExample;

public interface PtlogicactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int countByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int deleteByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int insert(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int insertSelective(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    List<Ptlogicact> selectByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int updateByExample(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);
}