package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.WorkorderItem;
import task.repository.model.WorkorderItemExample;

public interface WorkorderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int countByExample(WorkorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int deleteByExample(WorkorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int insert(WorkorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int insertSelective(WorkorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    List<WorkorderItem> selectByExample(WorkorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    WorkorderItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") WorkorderItem record, @Param("example") WorkorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int updateByExample(@Param("record") WorkorderItem record, @Param("example") WorkorderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int updateByPrimaryKeySelective(WorkorderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_ITEM
     *
     * @mbggenerated Thu Feb 19 13:47:00 CST 2015
     */
    int updateByPrimaryKey(WorkorderItem record);
}