package task.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import task.repository.model.WorkorderInfo;
import task.repository.model.WorkorderInfoExample;

public interface WorkorderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int countByExample(WorkorderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByExample(WorkorderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insert(WorkorderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int insertSelective(WorkorderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    List<WorkorderInfo> selectByExample(WorkorderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    WorkorderInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") WorkorderInfo record, @Param("example") WorkorderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByExample(@Param("record") WorkorderInfo record, @Param("example") WorkorderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKeySelective(WorkorderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.WORKORDER_INFO
     *
     * @mbggenerated Thu Feb 12 23:08:05 CST 2015
     */
    int updateByPrimaryKey(WorkorderInfo record);
}
